const products = [
  {
    name: 'Bronson Automatic Brown Eco Leather Watch',
    images: [
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Raquel Three-Hand Date Gold-Tone Stainless Steel Watch',
    images: [
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Modern Sophisticate Three-Hand Rose Gold-Tone Stainless Steel Watch',
    images: [
      { url: '/images/watch1.png' },
      { url: '/images/watch1.png' },
      { url: '/images/watch1.png' },
      { url: '/images/watch1.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Carlie Mini Three-Hand Stainless Steel Watch',
    images: [
      { url: '/images/watch2.png' },
      { url: '/images/watch2.png' },
      { url: '/images/watch2.png' },
      { url: '/images/watch2.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Hybrid Smartwatch HR Monroe Two-Tone Stainless Steel',
    images: [
      { url: '/images/watch3.png' },
      { url: '/images/watch3.png' },
      { url: '/images/watch3.png' },
      { url: '/images/watch3.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Jacqueline Three-Hand Date Rose Gold-Tone Stainless Steel Watch',
    images: [
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
      { url: '/images/watch6.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Scarlette Three-Hand Day-Date Stainless Steel Watch',
    images: [
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
      { url: '/images/watch5.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
  {
    name: 'Bronson Automatic Brown Eco Leather Watch',
    images: [
      { url: '/images/watch4.png' },
      { url: '/images/watch4.png' },
      { url: '/images/watch4.png' },
      { url: '/images/watch4.png' },
    ],
    description:
      'This 44mm Bronson features a black satin dial, automatic movement and brown eco leather strap.',
    category: 'Women',
    price: 89.99,
    countInStock: 10,
    productDetails: [
      { title: 'Case Size', value: '44 mm' },
      { title: 'Movement', value: 'Automatic' },
      { title: 'Platform', value: 'BRONSON' },
      { title: 'Strap Material', value: 'LiteHide™ Leather' },
      { title: 'Case Water Resistance', value: '5 ATM' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Fashio Color', value: 'Brown' },
      { title: 'Case Material', value: 'Stainless Steel' },
      { title: 'Strap Width', value: '22 mm' },
      { title: 'closure', value: 'Single Prong Strap Buckle' },
      { title: 'Crystal Type', value: 'Mineral' },
      { title: 'Battery Type', value: 'No Battery' },
    ],
  },
];

module.exports = products;
